name: generate galaga contribution graph

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate galaga contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'galaga'

      - name: push SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore(graph): update galaga contribution graph"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
